<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserDisplayGridView.aspx.cs" Inherits="ClickToCart.UserDisplayGridView" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            margin-top: 15px;
        }
        .auto-style2 {
            position: absolute;
            top: 681px;
            left: 1265px;
            z-index: 1;
            width: 181px;
            height: 42px;
        }
        .auto-style3 {
            position: absolute;
            top: 681px;
            z-index: 1;
            height: 43px;
            width: 183px;
            left: 990px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
          <link href="stylesheet1.css" rel="stylesheet" />
        <div>
                            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"   
                    BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px"   
                    CellPadding="3" DataKeyNames="PRODUCT_ID" AutoGenerateDeleteButton="True"   
                    AutoGenerateEditButton="True" onrowcancelingedit="GridView1_RowCancelingEdit"   
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"   
                    onrowupdating="GridView1_RowUpdating" CellSpacing="2" CssClass="auto-style1" DataSourceID="SqlDataSource1" Height="618px" Width="1480px">  

                    <Columns>  
                        
                        <asp:BoundField DataField="PRODUCT_ID" HeaderText="PRODUCT_ID" InsertVisible="False" ReadOnly="True" SortExpression="PRODUCT_ID" />
                         
                        <asp:TemplateField HeaderText="PRODUCT_NAME">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="PRODUCT_NAME" runat="server" Text='<%# Bind("PRODUCT_NAME") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("PRODUCT_NAME") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>  

                         <asp:TemplateField HeaderText="PRODUCT_DESCRIPTION">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="PRODUCT_DESCRIPTION" runat="server" Text='<%# Bind("PRODUCT_DESCRIPTION") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("PRODUCT_DESCRIPTION") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="CATEGORY_ID">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="CATEGORY_ID" runat="server" Text='<%# Bind("CATEGORY_ID") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("CATEGORY_ID") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 



                         <asp:TemplateField HeaderText="SUPPLIER_ID">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="SUPPLIER_ID" runat="server" Text='<%# Bind("SUPPLIER_ID") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label6" runat="server" Text='<%# Bind("SUPPLIER_ID") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 




                         <asp:TemplateField HeaderText="QUANTITY">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="QUANTITY" runat="server" Text='<%# Bind("QUANTITY") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label5" runat="server" Text='<%# Bind("QUANTITY") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 






                       
                    </Columns>  
                    <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />  
                    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />  
                    <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />  
                    <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />  
                    <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />  
                    <SortedAscendingCellStyle BackColor="#FFF1D4" />  
                    <SortedAscendingHeaderStyle BackColor="#B95C30" />  
                    <SortedDescendingCellStyle BackColor="#F1E5CE" />  
                    <SortedDescendingHeaderStyle BackColor="#93451F" />  
                </asp:GridView> 
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ClickToCartShopingConnectionString %>" SelectCommand="SELECT * FROM [PRODUCT]"  >

                            </asp:SqlDataSource>
                            <asp:Button ID="Button2" runat="server" CssClass="auto-style3" OnClick="Button2_Click" Text="Home" />
        </div>
          <asp:Button ID="Button1" runat="server" CssClass="auto-style2" OnClick="Button1_Click" Text="Back To Page" />
    </form>
</body>
</html>
