<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewCartDetails.aspx.cs" Inherits="ClickToCart.ViewCartDetails" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     
    <style type="text/css">
        .auto-style1 {
            position: absolute;
            top: 607px;
            left: 739px;
            z-index: 1;
            height: 48px;
            width: 211px;
        }
        .auto-style2 {
            position: absolute;
            top: 607px;
            left: 1004px;
            z-index: 1;
            width: 217px;
            height: 49px;
        }
        .auto-style3 {
            position: absolute;
            top: 609px;
            left: 1261px;
            z-index: 1;
            width: 224px;
            height: 47px;
            margin-right: 0px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
          <link href="stylesheet1.css" rel="stylesheet" />
        <div>
          <asp:GridView ID="grid" runat="server" AutoGenerateColumns="False"  
                    BackColor="#DEBA84" BorderColor="#000000" BorderStyle="None" BorderWidth="1px"  
                    CellPadding="3" DataKeyNames="cart_item_id" AutoGenerateDeleteButton="True"  
                    AutoGenerateEditButton="True" onrowcancelingedit="GridView1_RowCancelingEdit"  
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"  
                    onrowupdating="GridView1_RowUpdating" CellSpacing="2" Height="585px" Width="1493px">  
                <Columns >
                      <asp:boundfield datafield="PRODUCT_ID" readonly="true"   headertext="PRODUCT_ID"/>
           
                    <asp:boundfield datafield="PRODUCT_NAME" readonly="true"   headertext="Product_Name"/>
         
                    <asp:boundfield datafield="UNIT_PRICE" readonly="true"   headertext="UNIT_PRICE"/>
                     
                    
                    
                      <asp:boundfield datafield="TOTAL_PRICE" readonly="true"   headertext="TOTAL_PRICE"/>
                     <asp:boundfield datafield="user_name" readonly="true"   headertext="user_name"/>
                    <asp:boundfield datafield="date_cart" readonly="true"   headertext="date_cart"/>


                   <asp:TemplateField HeaderText="SelectedQuantity">  
                            <EditItemTemplate> 
                                <asp:DropDownList ID="ddlSelectQuantity" runat="server" AutoPostBack="false" >
<asp:ListItem>1</asp:ListItem>
<asp:ListItem>2</asp:ListItem>
<asp:ListItem>3</asp:ListItem>
<asp:ListItem>4</asp:ListItem>
<asp:ListItem>5</asp:ListItem>
<asp:ListItem>6</asp:ListItem>
<asp:ListItem>7</asp:ListItem>
<asp:ListItem>8</asp:ListItem>
<asp:ListItem>9</asp:ListItem>
<asp:ListItem>10</asp:ListItem>
</asp:DropDownList>

                                
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("quantity") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>  
                             
                     
                 
                   

                               
                  </Columns>
                </asp:GridView>
                    <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />  
                    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />  
                    <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />  
                    <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />  
                    <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />  
                    <SortedAscendingCellStyle BackColor="#FFF1D4" />  
                    <SortedAscendingHeaderStyle BackColor="#B95C30" />  
                    <SortedDescendingCellStyle BackColor="#F1E5CE" />  
                    <SortedDescendingHeaderStyle BackColor="#93451F" />  
                </asp:GridView>  


            <asp:Button ID="btnOrder" runat="server" Text="Place Order" OnClick="Order_Click" CssClass="auto-style1" />

        </div>
        <p>
            <asp:Button ID="Button2" runat="server" CssClass="auto-style2" OnClick="Button2_Click" Text="Back To Page" />
          </p>
        <p>
            <asp:Button ID="Button3" runat="server" CssClass="auto-style3" OnClick="Button3_Click" Text="Home" />
          </p>
        <p>

            &nbsp;</p>
    </form>
</body>
</html>
