<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewUserDisplayGridView.aspx.cs" Inherits="ClickToCart.ViewUserDisplayGridView" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            position: absolute;
            top: 675px;
            left: 1203px;
            z-index: 1;
            width: 213px;
            height: 52px;
        }
        .auto-style2 {
            position: absolute;
            top: 672px;
            left: 843px;
            z-index: 1;
            width: 227px;
            height: 50px;
            right: 447px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
          <asp:Button ID="Button2" runat="server" CssClass="auto-style2" OnClick="Button2_Click" Text="Home" />
          <link href="stylesheet1.css" rel="stylesheet" />
        <div>
            <asp:Button ID="Button1" runat="server" CssClass="auto-style1" OnClick="Button1_Click" Text="Back To Page" />
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"   
                    BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px"   
                    CellPadding="3" DataKeyNames="USERID" AutoGenerateDeleteButton="True"   
                    AutoGenerateEditButton="True" onrowcancelingedit="GridView1_RowCancelingEdit"   
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"   
                    onrowupdating="GridView1_RowUpdating" CellSpacing="2" DataSourceID="SqlDataSource1" Height="617px" Width="1534px">  
                    <Columns>  
                         <asp:BoundField DataField="USERID" HeaderText="USERID" InsertVisible="False" ReadOnly="True" SortExpression="USERID" />
                         <asp:TemplateField HeaderText="USER_NAME">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="USER_NAME" runat="server" Text='<%# Bind("USER_NAME") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("USER_NAME") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 
                            <asp:TemplateField HeaderText="FIRST_NAME">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="FIRST_NAME" runat="server" Text='<%# Bind("FIRST_NAME") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("FIRST_NAME") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                            <asp:TemplateField HeaderText="LAST_NAME">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="LAST_NAME" runat="server" Text='<%# Bind("LAST_NAME") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("LAST_NAME") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 
                            <asp:TemplateField HeaderText="CONTACT_NUMBER">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="CONTACT_NUMBER" runat="server" Text='<%# Bind("CONTACT_NUMBER") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label4" runat="server" Text='<%# Bind("CONTACT_NUMBER") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 
                         <asp:TemplateField HeaderText="ADDRESS">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="ADDRESS" runat="server" Text='<%# Bind("ADDRESS") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label5" runat="server" Text='<%# Bind("ADDRESS") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="CITY">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="CITY" runat="server" Text='<%# Bind("CITY") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label6" runat="server" Text='<%# Bind("CITY") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="ZIP">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="ZIP" runat="server" Text='<%# Bind("ZIP") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label7" runat="server" Text='<%# Bind("ZIP") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="COUNTRY">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="COUNTRY" runat="server" Text='<%# Bind("COUNTRY") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label8" runat="server" Text='<%# Bind("COUNTRY") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="EMAIL_ID">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="EMAIL_ID" runat="server" Text='<%# Bind("EMAIL_ID") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label9" runat="server" Text='<%# Bind("EMAIL_ID") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="PASSWORD">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="PASSWORD" runat="server" Text='<%# Bind("PASSWORD") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label10" runat="server" Text='<%# Bind("PASSWORD") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                      
                    </Columns>  
                    <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />  
                    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />  
                    <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />  
                    <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />  
                    <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />  
                    <SortedAscendingCellStyle BackColor="#FFF1D4" />  
                    <SortedAscendingHeaderStyle BackColor="#B95C30" />  
                    <SortedDescendingCellStyle BackColor="#F1E5CE" />  
                    <SortedDescendingHeaderStyle BackColor="#93451F" />  
                </asp:GridView>  
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ClickToCartShopingConnectionString2 %>" SelectCommand="SELECT * FROM [REGISTRATION_DETAILS]"></asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
